@extends('layouts.public')
@section('content')
@php
$heroImage=\App\Models\Setting::value('hero_image');
$heroUrl=$heroImage?Storage::url($heroImage):asset('images/dr-abdallah-homepage.jpg');
$heroStyle='background-image:linear-gradient(#10291f08,#10291f99),url('.$heroUrl.')';
@endphp
<section class="hero d-flex align-items-center"><div class="container py-5"><div class="row align-items-center g-5"><div class="col-lg-7"><p class="eyebrow">{{\App\Models\Setting::value('hero_eyebrow','Knowledge · Guidance · Community')}}</p><h1 class="display-title">{{\App\Models\Setting::value('hero_title','Dr. Abdallah Usman')}}<br><span style="color:var(--gold)">{{\App\Models\Setting::value('hero_highlight','Gadon Kaya')}}</span></h1><p class="lead my-4 col-xl-9">{{\App\Models\Setting::value('hero_description','Islamic scholar, Imam, lecturer and da‘wah teacher dedicated to making authentic knowledge accessible.')}}</p><a class="btn btn-gold btn-lg me-2" href="{{route('videos')}}">Watch latest lectures</a><a class="btn btn-outline-light btn-lg" href="{{route('about')}}">Read biography</a></div><div class="col-lg-5"><div class="hero-card" style="{{$heroStyle}}"><div><p class="eyebrow">Official digital archive</p><h3>Preserving lessons for generations</h3></div></div></div></div></div></section>
<section class="section"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><p class="eyebrow">About the scholar</p><h2 class="display-6">{{\App\Models\Setting::value('about_heading','A life devoted to learning and service')}}</h2></div><div class="col-lg-7"><p class="lead">{{\App\Models\Setting::value('about_excerpt','From Kano Legal School to the Islamic University of Madinah and Bayero University Kano, Dr. Gadon Kaya’s journey reflects a sustained commitment to scholarship, teaching and community guidance.')}}</p><a href="{{route('about')}}" class="link-success fw-bold">Discover his journey →</a></div></div></div></section>
<section class="section section-cream"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow">Watch and learn</p><h2>Latest lectures</h2></div><a href="{{route('videos')}}">View all →</a></div><div class="row g-4">@forelse($videos as $video)<div class="col-md-6 col-lg-4"><article class="card h-100 video-card"><div class="position-relative"><img class="card-img-top" loading="lazy" src="{{$video->thumbnail_url ?: 'https://i.ytimg.com/vi/'.$video->youtube_id.'/hqdefault.jpg'}}" alt="{{$video->title}}"><a class="play text-decoration-none" href="https://www.youtube.com/watch?v={{$video->youtube_id}}" aria-label="Watch {{$video->title}}">▶</a></div><div class="card-body"><p class="meta">{{$video->playlist}} · {{$video->published_at?->format('M j, Y')}}</p><h5>{{$video->title}}</h5></div></article></div>@empty<div class="col-12"><div class="empty">Latest YouTube lectures will appear here after the first sync.</div></div>@endforelse</div></div></section>
<section class="section section-dark"><div class="container"><div class="row justify-content-center"><div class="col-lg-8 text-center"><p class="eyebrow">A daily reminder</p><blockquote class="display-6">“{{\App\Models\Setting::value('daily_quote','Indeed, those who fear Allah among His servants are those who have knowledge.')}}”</blockquote><p class="text-white-50">{{\App\Models\Setting::value('daily_quote_source','Qur’an 35:28')}}</p></div></div></div></section>
<section class="section"><div class="container"><div class="d-flex justify-content-between mb-4"><h2>Latest articles</h2><a href="{{route('articles')}}">Browse library →</a></div><div class="row g-4">@forelse($articles as $a)<div class="col-md-4"><article class="card h-100"><div class="card-body p-4"><p class="meta">{{$a->published_at?->format('M j, Y')}}</p><h4><a class="text-dark text-decoration-none" href="{{route('article',$a)}}">{{$a->title}}</a></h4><p>{{Str::limit(strip_tags($a->body),130)}}</p></div></article></div>@empty<div class="empty">Articles are being prepared.</div>@endforelse</div></div></section>
@endsection
