<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,ContactController,PublicController};
use App\Http\Controllers\Admin\{ContentController,DashboardController,GalleryController,ManagementController,MessageController,SettingsController,YouTubeController};
Route::get('/',[PublicController::class,'home'])->name('home');
Route::get('/about',[PublicController::class,'about'])->name('about'); Route::get('/videos',[PublicController::class,'videos'])->name('videos');
Route::get('/articles',[PublicController::class,'articles'])->name('articles'); Route::get('/articles/{article:slug}',[PublicController::class,'article'])->name('article');
Route::get('/audio',[PublicController::class,'audio'])->name('audio'); Route::get('/events',[PublicController::class,'events'])->name('events'); Route::get('/gallery',[PublicController::class,'gallery'])->name('gallery'); Route::get('/books',[PublicController::class,'books'])->name('books');
Route::get('/tiktok',[PublicController::class,'tiktok'])->name('tiktok');
Route::get('/facebook',[PublicController::class,'facebook'])->name('facebook');
Route::get('/contact',[ContactController::class,'create'])->name('contact'); Route::post('/contact',[ContactController::class,'store'])->middleware('throttle:5,10')->name('contact.store');
Route::get('/search',[PublicController::class,'search'])->name('search'); Route::get('/language/{locale}',[PublicController::class,'locale'])->name('locale');
Route::get('/sitemap.xml', function(){ $urls=collect([route('home'),route('about'),route('videos'),route('tiktok'),route('facebook'),route('articles'),route('audio'),route('events'),route('gallery'),route('books'),route('contact')])->merge(\App\Models\Article::where('status','published')->get()->map(fn($a)=>route('article',$a))); return response()->view('sitemap',compact('urls'))->header('Content-Type','application/xml'); });
Route::middleware('guest')->group(function(){Route::get('/admin/login',[AuthController::class,'create'])->name('login');Route::post('/admin/login',[AuthController::class,'store'])->middleware('throttle:5,1')->name('login.store');});
Route::post('/logout',[AuthController::class,'destroy'])->middleware('auth')->name('logout');
Route::post('/admin/youtube/sync',[YouTubeController::class,'sync'])->middleware(['auth','role:super_admin,editor'])->name('admin.youtube.sync');
Route::middleware(['auth','role:super_admin,editor'])->prefix('admin')->name('admin.')->group(function(){Route::get('/gallery/{album}/images',[GalleryController::class,'index'])->name('gallery.images');Route::post('/gallery/{album}/images',[GalleryController::class,'store'])->name('gallery.images.store');Route::put('/gallery/images/{image}',[GalleryController::class,'update'])->name('gallery.images.update');Route::delete('/gallery/images/{image}',[GalleryController::class,'destroy'])->name('gallery.images.destroy');Route::post('/gallery/sync-official',[GalleryController::class,'sync'])->name('gallery.sync');});
Route::middleware(['auth','role:super_admin'])->prefix('admin')->name('admin.')->group(function(){Route::get('/users',[ManagementController::class,'users'])->name('users');Route::post('/users/{user?}',[ManagementController::class,'saveUser'])->name('users.save');Route::delete('/users/{user}',[ManagementController::class,'deleteUser'])->name('users.delete');Route::get('/activity',[ManagementController::class,'logs'])->name('activity');});
Route::middleware(['auth','role:super_admin,editor'])->prefix('admin')->name('admin.')->group(function(){Route::get('/media',[ManagementController::class,'media'])->name('media');Route::post('/media',[ManagementController::class,'upload'])->name('media.upload');Route::delete('/media/{media}',[ManagementController::class,'deleteMedia'])->name('media.delete');});
Route::prefix('admin')->name('admin.')->middleware(['auth','role:super_admin,editor'])->group(function(){Route::get('/',DashboardController::class)->name('dashboard');Route::get('/content/{type}',[ContentController::class,'index'])->name('content.index');Route::get('/content/{type}/create',[ContentController::class,'create'])->name('content.create');Route::post('/content/{type}',[ContentController::class,'store'])->name('content.store');Route::get('/content/{type}/{id}/edit',[ContentController::class,'edit'])->name('content.edit');Route::put('/content/{type}/{id}',[ContentController::class,'update'])->name('content.update');Route::delete('/content/{type}/{id}',[ContentController::class,'destroy'])->name('content.destroy');Route::get('/messages',[MessageController::class,'index'])->name('messages.index');Route::get('/messages/{message}',[MessageController::class,'show'])->name('messages.show');Route::delete('/messages/{message}',[MessageController::class,'destroy'])->name('messages.destroy');Route::get('/settings',[SettingsController::class,'edit'])->name('settings.edit');Route::put('/settings',[SettingsController::class,'update'])->name('settings.update');});
