@extends('layouts.admin') @section('heading',($item?'Edit ':'Add ').ucfirst($type)) @section('content')<form class="card border-0 shadow-sm p-4" method="post" enctype="multipart/form-data" action="{{$item?route('admin.content.update',[$type,$item->id]):route('admin.content.store',$type)}}">@csrf @if($item)@method('put')@endif @if($errors->any())<div class="alert alert-danger">Please correct the highlighted fields.</div>@endif
@php $value=fn($key,$default='')=>old($key,$item?->{$key}??$default); @endphp
<div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input class="form-control @error('title')is-invalid @enderror" name="title" value="{{$value('title')}}" required>@error('title')<div class="invalid-feedback">{{$message}}</div>@enderror</div>@if($type==='timeline')<div class="col-md-4"><label class="form-label">Year / period</label><input class="form-control" name="year" value="{{$value('year')}}" required></div>@else<div class="col-md-4"><label class="form-label">Slug (optional)</label><input class="form-control" name="slug" value="{{$value('slug')}}"></div>@endif
@if($type==='videos')<div class="col-md-4"><label class="form-label">YouTube video ID</label><input class="form-control" name="youtube_id" value="{{$value('youtube_id')}}"></div><div class="col-md-4"><label class="form-label">Playlist / category</label><input class="form-control" name="playlist" value="{{$value('playlist')}}"></div><div class="col-md-4"><label class="form-label">Thumbnail URL</label><input class="form-control" name="thumbnail_url" value="{{$value('thumbnail_url')}}"></div>@endif
@if($type==='articles')<div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['draft','published','scheduled'] as $s)<option @selected($value('status','draft')===$s)>{{$s}}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Publish date</label><input class="form-control" type="datetime-local" name="published_at" value="{{optional($item?->published_at)->format('Y-m-d\TH:i')}}"></div><div class="col-12"><label class="form-label">Article body</label><textarea id="editor" class="form-control" rows="14" name="body">{{$value('body')}}</textarea></div>@else<div class="col-12"><label class="form-label">Description</label><textarea id="editor" class="form-control" rows="7" name="description">{{$value('description')}}</textarea></div>@endif
@if($type==='events')<div class="col-md-4"><label class="form-label">Starts</label><input class="form-control" type="datetime-local" name="starts_at" value="{{optional($item?->starts_at)->format('Y-m-d\TH:i')}}" required></div><div class="col-md-4"><label class="form-label">Ends</label><input class="form-control" type="datetime-local" name="ends_at" value="{{optional($item?->ends_at)->format('Y-m-d\TH:i')}}"></div><div class="col-md-4"><label class="form-label">Venue</label><input class="form-control" name="venue" value="{{$value('venue')}}"></div>@endif
@if($type==='audio')<div class="col-md-6"><label class="form-label">MP3 file</label><input class="form-control" type="file" name="file_path" accept="audio/mpeg"></div><div class="col-md-6"><label class="form-label">Category</label><input class="form-control" name="category" value="{{$value('category')}}"></div>@endif
@if($type==='books')<div class="col-md-6"><label class="form-label">PDF file</label><input class="form-control" type="file" name="file_path" accept="application/pdf"></div><div class="col-md-6"><label class="form-label">Purchase / external URL</label><input class="form-control" name="external_url" value="{{$value('external_url')}}"></div>@endif
@if(in_array($type,['articles','audio','albums','books']))<div class="col-md-6"><label class="form-label">Cover image</label><input class="form-control" type="file" name="cover_image" accept="image/*"></div>@endif @if($type==='events')<div class="col-md-6"><label class="form-label">Featured image</label><input class="form-control" type="file" name="featured_image" accept="image/*"></div>@endif
@if($type==='videos')<div class="col-12"><label class="me-4"><input type="checkbox" name="is_featured" value="1" @checked($value('is_featured'))> Feature on homepage</label><label><input type="checkbox" name="is_hidden" value="1" @checked($value('is_hidden'))> Hide publicly</label></div>@endif @if($type==='timeline')<div class="col-md-4"><label>Display order</label><input class="form-control" type="number" name="sort_order" value="{{$value('sort_order',0)}}"></div>@endif</div><div class="mt-4"><button class="btn btn-success">Save</button><a class="btn btn-link" href="{{route('admin.content.index',$type)}}">Cancel</a></div></form>@endsection @push('scripts')<script src="https://cdn.jsdelivr.net/npm/tinymce@7/tinymce.min.js"></script><script>tinymce.init({selector:'#editor',menubar:false,plugins:'link lists',toolbar:'undo redo | blocks | bold italic | bullist numlist | link'});</script>@endpush
