@php
$setting=fn($key,$default=null)=>\App\Models\Setting::value($key,$default);
$siteName=$setting('site_name','Dr. Abdallah Usman Gadon Kaya');
$socials=['Facebook'=>$setting('facebook_url'),'TikTok'=>$setting('tiktok_url'),'YouTube'=>$setting('youtube_url'),'Instagram'=>$setting('instagram_url'),'WhatsApp'=>$setting('whatsapp_url'),'Telegram'=>$setting('telegram_url')];
@endphp
<!doctype html><html lang="{{app()->getLocale()}}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title',$siteName)</title><meta name="description" content="@yield('description',$setting('site_tagline','Official website of Dr. Abdallah Usman Gadon Kaya — Islamic scholarship, lectures, articles and events.'))">
<meta property="og:title" content="@yield('title',$siteName)"><meta property="og:description" content="@yield('description',$setting('site_tagline','Knowledge, guidance and community.'))"><meta property="og:type" content="website"><meta property="og:url" content="{{url()->current()}}">
@if($setting('favicon'))<link rel="icon" href="{{Storage::url($setting('favicon'))}}">@endif
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{asset('css/site.css')}}">@stack('head')
@if($setting('google_analytics_id'))<script async src="https://www.googletagmanager.com/gtag/js?id={{$setting('google_analytics_id')}}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config',@json($setting('google_analytics_id')));</script>@endif
</head><body>
@if($setting('maintenance_mode')==='1')<div class="alert alert-warning text-center rounded-0 mb-0">The website is being updated. Some information may be temporarily unavailable.</div>@endif
<div class="topbar"><div class="container d-flex justify-content-between"><span>بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم</span><span><a href="{{route('locale','en')}}">English</a> · <a href="{{route('locale','ha')}}">Hausa</a></span></div></div>
<nav class="navbar navbar-expand-lg navbar-dark sticky-top"><div class="container"><a class="navbar-brand" href="{{route('home')}}">@if($setting('logo'))<img src="{{Storage::url($setting('logo'))}}" alt="{{$siteName}}" style="height:46px;width:auto">@else<span class="brand-mark">GK</span>@endif<span>{{$siteName}}<small>{{$setting('site_tagline','Official Website')}}</small></span></a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav" aria-label="Open navigation"><span class="navbar-toggler-icon"></span></button><div id="nav" class="collapse navbar-collapse"><ul class="navbar-nav ms-auto">@foreach(['home','about','videos','tiktok','facebook','audio','articles','events','gallery','books','contact'] as $n)<li class="nav-item"><a class="nav-link {{request()->routeIs($n)?'active':''}}" href="{{route($n)}}">{{__('site.'.$n)}}</a></li>@endforeach</ul><form class="d-flex ms-lg-3" action="{{route('search')}}"><input class="form-control form-control-sm" name="q" required aria-label="Search"><button class="btn btn-gold btn-sm" aria-label="Submit search">⌕</button></form></div></div></nav>
<main>@if(session('success'))<div class="container mt-3"><div class="alert alert-success">{{session('success')}}</div></div>@endif @yield('content')</main>
<footer><div class="container py-5"><div class="row g-4"><div class="col-md-5"><h4>{{$siteName}}</h4><p>{{$setting('footer_description','Sharing authentic Islamic knowledge through lectures, scholarship and community service.')}}</p><div class="d-flex flex-wrap gap-2">@foreach($socials as $label=>$url)@if($url)<a class="btn btn-outline-light btn-sm" href="{{$url}}" target="_blank" rel="noopener">{{$label}}</a>@endif @endforeach</div></div><div class="col-6 col-md-3"><h6>Explore</h6><a href="{{route('about')}}">Biography</a><a href="{{route('videos')}}">Video Library</a><a href="{{route('tiktok')}}">TikTok Videos</a><a href="{{route('articles')}}">Articles</a></div><div class="col-6 col-md-4"><h6>Contact</h6>@if($setting('contact_email'))<a href="mailto:{{$setting('contact_email')}}">{{$setting('contact_email')}}</a>@endif @if($setting('contact_phone'))<a href="tel:{{$setting('contact_phone')}}">{{$setting('contact_phone')}}</a>@endif @if($setting('contact_address'))<p>{{$setting('contact_address')}}</p>@endif<a class="btn btn-outline-light btn-sm" href="{{route('contact')}}">Contact us</a></div></div><hr><small>© {{date('Y')}} {{$siteName}}. All rights reserved.</small></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>@stack('scripts')</body></html>
