<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\ActivityLog; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str;
class ContentController extends Controller {
 private array $map=['videos'=>\App\Models\Video::class,'articles'=>\App\Models\Article::class,'audio'=>\App\Models\AudioTrack::class,'events'=>\App\Models\Event::class,'albums'=>\App\Models\GalleryAlbum::class,'books'=>\App\Models\Book::class,'timeline'=>\App\Models\TimelineEntry::class];
 private function model($type){abort_unless(isset($this->map[$type]),404);return $this->map[$type];}
 public function index($type){$class=$this->model($type);$view=$type==='albums'?'admin.gallery.albums':'admin.content.index';return view($view,['type'=>$type,'items'=>$class::latest()->paginate(20)]);}
 public function create($type){$this->model($type);return view('admin.content.form',['type'=>$type,'item'=>null]);}
 public function store(Request $r,$type){$class=$this->model($type);$data=$this->validated($r,$type);$item=$class::create($this->uploads($r,$data,$type));$this->log('created',$item);return redirect()->route('admin.content.index',$type)->with('success','Saved successfully.');}
 public function edit($type,$id){$class=$this->model($type);return view('admin.content.form',['type'=>$type,'item'=>$class::findOrFail($id)]);}
 public function update(Request $r,$type,$id){$class=$this->model($type);$item=$class::findOrFail($id);$item->update($this->uploads($r,$this->validated($r,$type),$type));$this->log('updated',$item);return redirect()->route('admin.content.index',$type)->with('success','Updated successfully.');}
 public function destroy($type,$id){$class=$this->model($type);$item=$class::findOrFail($id);$this->log('deleted',$item);foreach(['cover_image','featured_image','file_path'] as $field)if(!empty($item->{$field}))Storage::disk('public')->delete($item->{$field});$item->delete();return back()->with('success','Deleted.');}
 private function validated(Request $r,$type){$rules=['title'=>'required|max:255','slug'=>'nullable|max:255','description'=>'nullable|string','body'=>'nullable|string','status'=>'nullable|in:draft,published,scheduled','published_at'=>'nullable|date','starts_at'=>'nullable|date','ends_at'=>'nullable|date|after_or_equal:starts_at','venue'=>'nullable|max:255','youtube_id'=>'nullable|max:30','thumbnail_url'=>'nullable|url|max:500','playlist'=>'nullable|max:100','duration'=>'nullable|max:30','category'=>'nullable|max:100','external_url'=>'nullable|url|max:500','year'=>'nullable|max:30','sort_order'=>'nullable|integer|min:0','is_featured'=>'nullable|boolean','is_hidden'=>'nullable|boolean','is_recurring'=>'nullable|boolean','cover_image'=>'nullable|image|max:5120','featured_image'=>'nullable|image|max:5120','file_path'=>'nullable|file|mimes:mp3,pdf|max:51200']; if($type==='timeline'){$rules['title']='required|max:255';$rules['year']='required|max:30';} if($type==='audio'&&!$r->route('id'))$rules['file_path']='required|file|mimes:mp3|max:51200'; if($type==='events')$rules['starts_at']='required|date'; if($type==='articles')$rules['body']='required|string'; return $r->validate($rules);}
 private function uploads(Request $r,$data,$type){if($type!=='timeline'&&empty($data['slug']))$data['slug']=Str::slug($data['title']).'-'.Str::lower(Str::random(5));foreach(['cover_image','featured_image','file_path'] as $f)if($r->hasFile($f))$data[$f]=$r->file($f)->store($type,'public');if($type==='videos'){foreach(['is_featured','is_hidden'] as $b)$data[$b]=$r->boolean($b);}if($type==='events')$data['is_recurring']=$r->boolean('is_recurring');if(isset($data['body']))$data['body']=$this->clean($data['body']);if(isset($data['description']))$data['description']=$this->clean($data['description']);return array_filter($data,fn($v)=>$v!==null);}
 private function clean($html){return preg_replace('#<(script|iframe|object|embed)[^>]*>.*?</\\1>#is','',$html);}
 private function log($action,$item){ActivityLog::create(['user_id'=>auth()->id(),'action'=>$action,'subject_type'=>get_class($item),'subject_id'=>$item->id]);}
}
